[package]
name = "gdio"
version = "1.0.1-stable"
edition = "2024"
description = "CLI tool for managing Godot Engine projects, editor versions, addons and export templates."

[dependencies]
clap = { version = "4", features = ["derive"] }
clap_complete = "4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
dirs = "6"
reqwest = { version = "0.13.4", features = ["json", "stream", "rustls"], default-features = false }
zip = "8.6.0"
tokio = { version = "1", features = ["full"] }
dialoguer = { version = "0.12.0", features = ["fuzzy-select"] }
console = "0.16.4"
flate2 = "1"
walkdir = "2"
anyhow = "1"
futures-util = "0.3"
indicatif = "0.18.6"
tempfile = "3"
toml = "1"
timeago = "0.6"
arboard = "3"
ratatui = "0.30.2"
unicode-width = "0.2.2"
crossterm = "0.29"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
overflow-checks = false
